import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/app/_components/ui/toaster";
import QueryProvider from "./_provider/query-provider";

import Nav from "./_components/nav";
import { cn } from "./_lib/utils";
import Main from "./_components/main";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "flex min-h-screen w-full bg-white text-black"
      )}>
        <QueryProvider>
          <Nav />
          <Main> {children}</Main>
         
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
